version: '3.8'
services:
  tattoo-browser-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
  test-tattoo-browser-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
